### ISSUE TITLE
Calling PHPStan\Mockery\Type\Expects::with() is not covered by backward compatibility promise. 

### ISSUE THREAD

**Issue by ruudk** [phpstan/phpstan-mockery#33] opened 2021-06-10 09:44 UTC
When upgrading from phpstan/phpstan 0.12.88 to 0.12.89 I'm getting a lot of errors like this:
```
Calling PHPStan\Mockery\Type\Expects::with() is not covered by backward compatibility promise. The
         method might change in a minor PHPStan version.
         💡 If you think it should be covered by backward compatibility promise, open a discussion:
            https://github.com/phpstan/phpstan/discussions

            See also:
            https://phpstan.org/developing-extensions/backward-compatibility-promise
```

I see that a fix has been pushed for `phpstan-phpunit`. Should the same type of fix be done here as well?

**Comment by ondrejmirtes** [comment] 2021-06-10 11:27
Please post a piece of code that reproduces this problem. I'm not aware of anything in phpstan-phpunit that would be causing a similar problem.

**Comment by ruudk** [comment] 2021-06-10 11:31
I'm sorry for not being clear. I saw a commit on `phpstan-phpunit` that speaks about backwards compatibility, similar to the error I'm getting: https://github.com/phpstan/phpstan-phpunit/commit/151d71b28f3d1b8aa517fc44bcb6ff2789153016

This is my code:
```php
/**
 * @var MockInterface&DraftRepository
 */
private MockInterface $draftRepository;

// ...

$this->draftRepository->expects('getActiveByUser')
    ->with($user)
    ->andReturn(new Draft());
```

**Comment by ondrejmirtes** [comment] 2021-06-10 11:42
In PHPUnit it was about something else - fixing a situation where PHPStan-specific code was marked as an error because it used something not covered by BC promise - a legit issue.

In this case PHPStan is reporting normal analyzed code like that, which it shouldn't. I'm gonna look into it.

**Comment by ondrejmirtes** [comment] 2021-06-10 12:15
I think I fixed it: https://github.com/phpstan/phpstan-mockery/commit/7cc74bf434b3c2190f7f4cfc08c74f7c0b65667f

Please try phpstan-mockery 0.12.14 to see if it works.

**Closed as completed by ondrejmirtes** 2021-06-10 12:15 UTC

**Comment by ruudk** [comment] 2021-06-14 08:45
Seems to be solved. Thanks @ondrejmirtes 💙
